spring:
  data:
    redis:
      host: localhost
      port: 6379

api:
  github:
    key: ${GITHUB_API_KEY}
  gemini:
    key: ${GEMINI_API_KEY}
  groq:
    key: ${GROQ_API_KEY}

cloudinary:
  url: ${CLOUDINARY_URL}

jwt:
  secret: ${JWT_SECRET}

logging:
  level:
    root: INFO
    com.codescope.backend: DEBUG
    org.springframework.web.reactive.function.client: DEBUG
